language: node_js
node_js:
- 6
script:
- npm run coverage
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_aa028baec1b7_key -iv $encrypted_aa028baec1b7_iv
  -in test/fixtures/gcs-key.json.enc -out test/fixtures/gcs-key.json -d
